- name: "Check if KVv2 engine '{{ secret_base_path }}' exists"
  community.hashi_vault.vault_read:
    url: "http://127.0.0.1:8200"
    token: "{{ vaultserver_token }}"
    path: "sys/mounts/{{ secret_base_path }}"
  register: kv_mount_check
  delegate_to: vaultserver
  when: current_secret.type == "kv"
  ignore_errors: true
  no_log: false

- name: "Create KVv2 engine '{{ secret_base_path }}' if it doesn't exist"
  community.hashi_vault.vault_write:
    url: "http://127.0.0.1:8200"
    token: "{{ vaultserver_token }}"
    path: "sys/mounts/{{ secret_base_path }}"
    data:
      type: "kv"
      options:
        version: "2"
  when: current_secret.type == "kv" and kv_mount_check.failed
  delegate_to: vaultserver


- name: "Create/Update KV secret: {{ current_secret.name }}"
  community.hashi_vault.vault_kv2_write:
    url: "http://127.0.0.1:8200"
    token: "{{ vaultserver_token }}"
    engine_mount_point: "{{ secret_base_path }}"
    path: "secrets/{{ current_secret.name }}"
    data: "{{ current_secret.data }}"
  when: current_secret.type == "kv"
  no_log: false
  delegate_to: vaultserver


- name: "Manage Transit Secret: {{ current_secret.name }}"
  when: current_secret.type == "transit"
  delegate_to: vaultserver
  block:
    - name: Set secret-specific mount path
      ansible.builtin.set_fact:
        mount_path: "{{ secret_base_path }}-{{ current_secret.type }}-{{ current_secret.name }}"

    - name: "Check if Transit engine '{{ mount_path }}' exists"
      community.hashi_vault.vault_read:
        url: "http://127.0.0.1:8200"
        token: "{{ vaultserver_token }}"
        path: "sys/mounts/{{ mount_path }}"
      register: transit_mount_check
      ignore_errors: true
      no_log: false

    - name: "Create Transit engine '{{ mount_path }}' if it doesn't exist"
      community.hashi_vault.vault_write:
        url: "http://127.0.0.1:8200"
        token: "{{ vaultserver_token }}"
        path: "sys/mounts/{{ mount_path }}"
        data:
          type: "transit"
      when: transit_mount_check.failed

    - name: "Create/Update Transit key {{ current_secret.name }}"
      community.hashi_vault.vault_write:
        url: "http://127.0.0.1:8200"
        token: "{{ vaultserver_token }}"
        path: "{{ mount_path }}/keys/{{ current_secret.name }}"
        data:
          type: "{{ current_secret.key_type }}"

    - name: "Configure Transit key {{ current_secret.name }}"
      community.hashi_vault.vault_write:
        url: "http://127.0.0.1:8200"
        token: "{{ vaultserver_token }}"
        path: "{{ mount_path }}/keys/{{ current_secret.name }}/config"
        data: "{{ current_secret.config }}"
      when: current_secret.config is defined

    - name: "⭐️ DEBUG: Your .NET JWKS Endpoint URL"
      ansible.builtin.debug:
        msg: "Your .NET app ({{ current_secret.name }}) can use this JWKS URL: http://127.0.0.1:8200/v1/{{ mount_path }}/jwks/{{ current_secret.name }}"


- name: "Manage Database Engine: {{ current_secret.name }}"
  when: current_secret.type == "database"
  block:
    - name: Set secret-specific mount path
      ansible.builtin.set_fact:
        mount_path: "{{ secret_base_path }}-{{ current_secret.type }}-{{ current_secret.name }}"

    - name: "Check if Database engine '{{ mount_path }}' exists"
      community.hashi_vault.vault_read:
        url: "http://127.0.0.1:8200"
        token: "{{ vaultserver_token }}"
        path: "sys/mounts/{{ mount_path }}"
      register: db_mount_check
      ignore_errors: true
      no_log: false
      delegate_to: vaultserver 
      
    - name: "Create Database engine '{{ mount_path }}' if it doesn't exist"
      community.hashi_vault.vault_write:
        url: "http://127.0.0.1:8200"
        token: "{{ vaultserver_token }}"
        path: "sys/mounts/{{ mount_path }}"
        data:
          type: "database"
      when: db_mount_check.failed
      register: vault_mount_status
      delegate_to: vaultserver 

    - name: "Fetch '{{ current_secret.name }}' superuser credentials from K8s"
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: "{{ current_secret.name }}-superuser-creds"
        namespace: "{{ current_secret.credentials_namespace }}"
      register: k8s_secret_result
      when: vault_mount_status.changed
      no_log: false
      delegate_to: masternode 

    - name: "Register K8s secret password into 'pg_superuser_password' var"
      ansible.builtin.set_fact:
        pg_superuser_password: "{{ k8s_secret_result.resources[0].data.password | b64decode }}"
      when: vault_mount_status.changed
      no_log: false

    - name: "Configure database credentials rotation for {{ current_secret.name }}"
      when:
        - vault_mount_status.changed
      delegate_to: vaultserver
      block:
        - name: Configure the database connection details
          community.hashi_vault.vault_database_connection_configure:
            engine_mount_point: "{{ mount_path }}"
            token: "{{ vaultserver_token }}"
            url: "http://127.0.0.1:8200"
            plugin_name: "postgresql-database-plugin"
            connection_name: "{{ current_secret.name }}-database-connection"
            connection_url: "postgresql://{{'{{username}}'}}:{{'{{password}}'}}@{{ current_secret.db_url }}:{{ current_secret.db_port }}/{{ current_secret.name }}?sslmode=verify-full&sslrootcert=/opt/vault/tls/root_ca.crt"
            connection_password: "{{ pg_superuser_password }}"
            connection_username: "postgres"
            allowed_roles: "{{ current_secret.roles | default([]) | map(attribute='name') | map('regex_replace', '^', current_secret.name ~ '-') | list }}"
          no_log: false
    
        - name: Create dynamic client roles for the application
          community.hashi_vault.vault_database_role_create:
            engine_mount_point: "{{ mount_path }}"
            token: "{{ vaultserver_token }}"
            url: "http://127.0.0.1:8200"
            connection_name: "{{ current_secret.name }}-database-connection"
            # Resulting Name: platform-readwrite-role
            role_name: "{{ current_secret.name }}-{{ item.name }}"
            creation_statements: "{{ item.creation_statements }}"
            default_ttl: "{{ item.default_ttl }}"
            max_ttl: "{{ item.max_ttl }}"
          loop: "{{ current_secret.roles | default([]) }}"
          loop_control:
            label: "{{ current_secret.name }}-{{ item.name }}"
    
        - name: CRITICAL - Rotate the 'postgres' root password
          community.hashi_vault.vault_database_rotate_root_credentials:
            engine_mount_point: "{{ mount_path }}"
            token: "{{ vaultserver_token }}"
            url: "http://127.0.0.1:8200"
            connection_name: "{{ current_secret.name }}-database-connection"
          no_log: false
    
        - name: "Clean up K8s superuser secret {{ current_secret.name }}-superuser-creds"
          kubernetes.core.k8s:
            api_version: v1
            kind: Secret
            name: "{{ current_secret.name }}-superuser-creds"
            namespace: "{{ current_secret.credentials_namespace }}"
            state: absent
          no_log: false
          delegate_to: masternode
