apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamly-api
  namespace: jamly-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jamly-api
  template:
    metadata:
      labels:
        app: jamly-api
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: api
        image: ghcr.io/t-esp-asstagj/api:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: "staging"
        - name: REDIS_URL
          value: "redis://redis.jamly-api.svc.cluster.local:6379"
        - name: MERCURE_PUBLIC_URL
          value: "https://api.jamly.eu/.well-known/mercure"
        envFrom:
        - secretRef:
            name: jamly-api-secrets
