apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: jamly-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
