[frontend_node]
frontendnode ansible_host=127.0.0.1 ansible_port=3500 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/frontend_node/virtualbox/private_key'

[database_node]
databasenode ansible_host=127.0.0.1 ansible_port=3501 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/database_node/virtualbox/private_key'

[backend_node]
backendnode ansible_host=127.0.0.1 ansible_port=3502 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/backend_node/virtualbox/private_key'

[master_node]
masternode ansible_host=127.0.0.1 ansible_port=3503 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/master_node/virtualbox/private_key'

[api_node]
apinode ansible_host=127.0.0.1 ansible_port=3504 ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/api_node/virtualbox/private_key'

[gateway]
gatewayserver ansible_python_interpreter=/usr/local/bin/python3.11 ansible_host=127.0.0.1 ansible_port=2222 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/gateway/virtualbox/private_key'

[vault]
vaultserver ansible_host=127.0.0.1 ansible_port=3505 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/vault/virtualbox/private_key'


[pki]
pkiserver ansible_host=127.0.0.1 ansible_port=3506 ansible_ssh_private_key_file='../vagrant/.vagrant/machines/pki/virtualbox/private_key'
