- name: Check if the intermediate CA secrets engine exists
  ansible.builtin.shell:
    cmd: "vault roles list -tls-skip-verify | grep -q platform_internal_intermediate_ca/"
  register: intermediate_ca_check
  changed_when: false
  failed_when: false