apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jamly-api-secrets
  namespace: jamly-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: jamly-api-secrets
    creationPolicy: Owner
  data:
  - secretKey: APP_SECRET
    remoteRef:
      key: app-secret
  - secretKey: MERCURE_JWT_SECRET
    remoteRef:
      key: mercure-jwt-secret
  - secretKey: DATABASE_URL
    remoteRef:
      key: database-url
  - secretKey: MERCURE_PUBLIC_URL
    remoteRef:
      key: mercure-public-url
