apiVersion: v1
kind: Secret
metadata:
  name: longhorn-r2-backups
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: REPLACE_ME
  AWS_ENDPOINTS: https://example-account.r2.cloudflarestorage.com
  AWS_SECRET_ACCESS_KEY: REPLACE_ME
