apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: tls-platform-database-pooler
  namespace: database
spec:
  parentRefs:
  - name: database-gateway
    kind: Gateway
    namespace: database
    sectionName: pgsql
    backendRefs:
    - name: pooler-platform-rw
      kind: Service
      port: 5432
      namespace: database

