---
# Variables for Kubernetes control plane nodes
# Only environment-specific overrides — defaults are in roles/k8s_control_plane/defaults/main.yml

k8s_cluster_name: "epitech-k8s-cluster"

# Cilium CNI configuration
cilium_hubble_enabled: true

# enable Helm install
install_helm: true
