{
 "title": "Network Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pf_state_inserts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pf_state_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "packets in blocked total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pf_ipv4_packets_in_blocked_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}