apiVersion: v1
kind: Secret
metadata:
  name: vault-token-g955r
  annotations:
    kubernetes.io/service-account.name: vault
  labels:
    vault-token-for: "vault-sa"
type: kubernetes.io/service-account-token
