apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-pki-token
  annotations:
    kubernetes.io/service-account.name: cert-manager-sa
  labels:
    token-for: "cert-sa"
type: kubernetes.io/service-account-token
