apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: "service-advertisements"
  labels:
    purpose: announce-services
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector: {}