- name: Check if Vault is already installed
  ansible.builtin.command: command -v vault
  register: vault_check
  changed_when: false
  failed_when: false

- name: Download and install HashiCorp GPG key
  ansible.builtin.shell:
    cmd: "wget -qO- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg"
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg 
  when: vault_check.rc != 0

- name: Add HashiCorp repository
  ansible.builtin.shell:
    cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list'
    creates: /etc/apt/sources.list.d/hashicorp.list
  when: vault_check.rc != 0

- name: Update apt cache and upgrade system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
  when: vault_check.rc != 0

- name: Install vault
  ansible.builtin.apt:
    name: vault
    state: present
  register: vault_install_status
  when: vault_check.rc != 0

- name: Reboot for changes to take effect
  ansible.builtin.reboot:
  when: vault_install_status.changed