name: 🏗️ Manual Deployment PR (Infra)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      include_tickets:
        description: 'Include ticket summary'
        required: false
        default: true
        type: boolean
      source_branch:
        description: 'Source branch'
        required: false
        default: 'staging'
        type: string

jobs:
  create-deployment-pr:
    uses: T-ESP-ASSTAGJ/infra/.github/workflows/_reusable/staging-to-main.yml@main
    with:
      repository_name: "infra"
      environment: ${{ inputs.environment }}
      source_branch: ${{ inputs.source_branch }}
      include_tickets: ${{ inputs.include_tickets }}
      reviewers: "devops-team,infrastructure-lead,security-team"
      team_reviewers: "infrastructure-team,security-team"
    secrets:
      AUTO_DEPLOY_TOKEN: ${{ secrets.AUTO_DEPLOY_TOKEN }}