# LAN-1: Main Lan Configuration
subnet 192.168.10.0 netmask 255.255.255.0 {
  option domain-name-servers 192.168.10.1;
  range 192.168.10.10 192.168.10.20;
  option routers 192.168.10.1;
  option broadcast-address 192.168.10.255;

  host frontendserver {
    hardware ethernet 08:00:27:12:34:60;
    fixed-address 192.168.10.10;
  }
  
  host databaseserver {
    hardware ethernet 08:00:27:12:34:61;
    fixed-address 192.168.10.11;
  }

  host backendserver {
    hardware ethernet 08:00:27:12:34:62;
    fixed-address 192.168.10.12;
  }

  host controlserver {
    hardware ethernet 08:00:27:12:34:63;
    fixed-address 192.168.10.13;
  }

  host apiserver {
    hardware ethernet 08:00:27:12:34:64;
    fixed-address 192.168.10.14;
  }
  
  host vaultserver {
    hardware ethernet 08:00:27:12:34:69;
    fixed-address 192.168.10.15;
  }
    
  host pkiserver {
    hardware ethernet 08:00:27:12:34:70;
    fixed-address 192.168.10.16;
  }
}